### ISSUE TITLE
"OverflowError: cannot fit 'int' into an index-sized integer" revisited...

### ISSUE THREAD

**Issue by ghost** [Lyrrad/multidrive#1]
I'd like to say that your multidrive work is incredible.  This is exactly what I've been looking for on Linux, and it is truly useful.  Thank you so much for doing this!

Unfortunately I'm running into a different issue with uploading large files on a 32-bit system than you originally reported/worked on regarding the "requests-toolbelt" encoder.  I was hoping you might have some insight.  I'm a relative newbie in terms of Python, and after spending a lot of time digging into the requests-toolbelt encoder, I'm finding that this "len" issue is beyond my capabilities at the present time.

I'm using multidrive on a 32-bit Linux system (running Ubuntu 14.04), and I've pulled down and installed the latest requests-toolbelt package (0.4.0), requests 2.6.0, etc.

With the latest requests-toolbelt (including the "bug/80" fix), multidrive can upload a 4GB file (for example) to Google Drive without an issue.  Unfortunately however uploading the same file to Cloud Drive fails with an "int" OverflowError involving "len".  This is the traceback that I get:

```
test@gandalf:~/projects/multidrive$ python3 multidrive.py -s clouddrive -a upload -l ./testfile
Traceback (most recent call last):
  File "multidrive.py", line 199, in <module>
    main()
  File "multidrive.py", line 89, in main
    overwrite=args.overwrite)
  File "/home/test/projects/multidrive/clouddrivestorageservice.py", line 390, in upload
    multipart_hash_file=cur_hash_file)
  File "/home/test/projects/multidrive/clouddrivestorageservice.py", line 135, in http_request
    data = MultipartEncoder(fields=multipart_encoder_fields)
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt-0.4.0-py3.4.egg/requests_toolbelt/multipart/encoder.py", line 120, in __init__
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt-0.4.0-py3.4.egg/requests_toolbelt/multipart/encoder.py", line 241, in _prepare_parts
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt-0.4.0-py3.4.egg/requests_toolbelt/multipart/encoder.py", line 241, in <listcomp>
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt-0.4.0-py3.4.egg/requests_toolbelt/multipart/encoder.py", line 453, in from_field
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt-0.4.0-py3.4.egg/requests_toolbelt/multipart/encoder.py", line 446, in __init__
  File "/usr/local/lib/python3.4/dist-packages/requests-2.6.0-py3.4.egg/requests/utils.py", line 52, in super_len
    return len(o)
OverflowError: cannot fit 'int' into an index-sized integer
test@gandalf:~/projects/multidrive$
```

Do you have any ideas?  Anything that you could do to help address this would be so awesome...again your work here is simply too cool.

Thanks!!

**Comment by Lyrrad** [comment]
Yeah, I noticed this issue too, but I wasn't able to fix it easily.  I'll ping a maintainer of the requests- toolbelt module to see what they think.

I know it worked after the initial fix, but I might have refactored my code afterwards to cause this issue to happen in a different way.

**Comment by ghost** [comment]
Thanks!  I'm actually running this on a Pi 2 with an SSD, as a low-power background bulk uploader to Cloud Drive.  However I need to be able to upload large files, as currently the only other option to upload large files is the Windows desktop app.  As this is an ARM device, a 64-bit environment is not an option...  Again I greatly appreciate any help you can provide!

**Comment by Lyrrad** [comment]
I think I figured out the issue and a fix.  I'll test it out a bit but I should have it updated soon.

**Comment by ghost** [comment]
Works like a charm :-)
